#!/bin/bash

usage_and_exit() {
  echo "Usage: ${0} start|stop"
  exit 1
}

if [[ -z "${1}" ]]; then
  echo "No argument provided."
  usage_and_exit
fi

if [[ "${1}" != "start" ]] && [[ "${1}" != "stop" ]]; then
  echo "Argument does not match 'start' or 'stop."
  usage_and_exit
fi

interface_is_up() {
  local interface="${1}"

  if ip a show "${interface}" up &>/dev/null; then
    return 0
  else
    return 1
  fi
}

stop_dhcp_server_if_running() {
  if /etc/init.d/isc-dhcp-server status &>/dev/null; then
    echo "DHCP server is running - stopping..."
    /etc/init.d/isc-dhcp-server stop
  else
    echo "DHCP server is not running - doing nothing..."
  fi
}

delete_dhcp_pid_if_exists() {
  local pid_file="/var/run/dhcpd.pid"

  # Delete DHCP pid file if it exists
  if [[ -f "${pid_file}" ]]; then
    echo "DHCP pid file exists - deleting..."
    rm "${pid_file}"
  else
    echo "DHCP pid file does not exist - doing nothing..."
  fi
}

set_static_ip() {
  local interface="${1}"
  local ip="${2}"

  echo "Setting static IP for ${interface}: ${ip}"
  ifconfig "${interface}" "${ip}"
}

main() {
  stop_dhcp_server_if_running
  delete_dhcp_pid_if_exists

  if [[ "${1}" == "start" ]]; then
    if interface_is_up usb0; then

      set_static_ip usb0 192.168.64.1

      echo "USB0 interface is up - starting DHCP server..."
      /etc/init.d/isc-dhcp-server start

    else

      echo "USB0 interface is not up - doing nothing..."

    fi
  fi
}

main "$@"
exit 0
