#!/bin/sh

get_variables() {
    ROOT_PART_DEV=$(findmnt / -o source -n)
    ROOT_PART_NAME=$(echo "$ROOT_PART_DEV" | cut -d "/" -f 3)
    ROOT_DEV_NAME=$(echo /sys/block/*/"${ROOT_PART_NAME}" | cut -d "/" -f 4)
    ROOT_DEV="/dev/${ROOT_DEV_NAME}"
    ROOT_PART_NUM=$(cat "/sys/block/${ROOT_DEV_NAME}/${ROOT_PART_NAME}/partition")

    OLD_DISKID=$(fdisk -l "$ROOT_DEV" | sed -n 's/Disk identifier: 0x\([^ ]*\)/\1/p')

    ROOT_DEV_SIZE=$(cat "/sys/block/${ROOT_DEV_NAME}/size")
    TARGET_END=$((ROOT_DEV_SIZE - 1))

    PARTITION_TABLE=$(parted -m "$ROOT_DEV" unit s print | tr -d 's')

    EXT_PART_LINE=$(echo "$PARTITION_TABLE" | grep ":::;" | head -n 1)
    EXT_PART_NUM=$(echo "$EXT_PART_LINE" | cut -d ":" -f 1)
}

fix_partuuid() {
    DISKID="$(fdisk -l "$ROOT_DEV" | sed -n 's/Disk identifier: 0x\([^ ]*\)/\1/p')"

    sed -i "s/${OLD_DISKID}/${DISKID}/g" /etc/fstab
    sed -i "s/${OLD_DISKID}/${DISKID}/" /boot/cmdline.txt
}

expand_filesystem() {
    get_variables

    # Note the Yes in the command to confirm the message:
    # Warning: Partition /dev/mmcblk0p2 is being used. Are you sure you want to continue?
    # This is not required in the second call

    # Resize extended partition
    echo Yes | parted "${ROOT_DEV}" ---pretend-input-tty resizepart "${EXT_PART_NUM}" "${TARGET_END}"s

    # Resize rootfs partition
    parted "${ROOT_DEV}" ---pretend-input-tty <<EOF
resizepart
${ROOT_PART_NUM}
${TARGET_END}s
quit
EOF

    partprobe "$ROOT_DEV"
    fix_partuuid
    resize2fs "$ROOT_PART_DEV"

    return 0
}


mount -t devtmpfs none /dev
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /run
mkdir -p /run/systemd

mount /boot
mount / -o remount,ro


# Load kernel modules to perform i2c operations
modprobe i2c-bcm2835
modprobe i2c-dev

if i2cping 0x11; then
    # If pi-top[4], avoid OLED from timing out
    # Make RPi take control over OLED and reset screen
    i2cset -y 1 0x11 0x14 3
fi

if ! grep -q splash /boot/cmdline.txt; then
    sed -i "s/ quiet//g" /boot/cmdline.txt
fi
sed -i 's| init=/sbin/pt-os-init||' /boot/cmdline.txt

mount /boot -o remount,ro
sync

echo 1 > /proc/sys/kernel/sysrq

expand_filesystem >>/dev/null

if i2cping 0x11; then
    # Let hub control OLED
    i2cset -y 1 0x11 0x14 0
fi

umount /boot
mount / -o remount,ro
sync

reboot -f
