#!/bin/bash
###############################################################
#                Unofficial 'Bash strict mode'                #
# http://redsymbol.net/articles/unofficial-bash-strict-mode/  #
###############################################################
set -euo pipefail
IFS=$'\n\t'
###############################################################

echo "#################################################"
echo "##   'run-sonic-pi-server' is now deprecated   ##"
echo "##        Please use 'sonic-pi-server'         ##"
echo "#################################################"

exit 1
