name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target_architecture: ["arm64", "armhf", "amd64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Patch changelog (snapshot)
        uses: pi-top/git-debian-changelog-bump-action@develop
        with:
          release: false

      # ------------------------------------------------------------------------

      - name: Build Debian package
        uses: pi-top/deb-build-docker@develop
        with:
          target_architecture: ${{ matrix.target_architecture }}
          docker_image: pitop/deb-build-img:bullseye-develop
          path: ./artifacts

      # ------------------------------------------------------------------------

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      # - name: Upload Debian package artifacts
      #   uses: pi-top/debian-package-artifact-uploader@master
      #   with:
      #     path: ./artifacts
      #     deb_only: true
      #     # deb_only_name: "deb"
      #     deb_src_only: true
      #     # deb_src_name: "deb-src"
      #     prefix: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-"
