name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  DEB_BUILD_DOCKER_IMAGE: "pitop/deb-build-img"
  DEB_BUILD_DOCKER_TAG: "buster-backports-develop"
  CHANGELOG_AUTHOR_NAME: "pi-top"
  CHANGELOG_AUTHOR_EMAIL: "deb-maintainers@pi-top.com"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # TODO: parse changelog in previous step
        # target_architecture: ["arm64", "armhf", "amd64"]
        target_architecture: ["amd64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Patch changelog (snapshot)
        uses: pi-top/git-debian-changelog-bump-action@develop
        with:
          release: false
          author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
          author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}

      # ------------------------------------------------------------------------

      - name: Build Debian package
        uses: pi-top/deb-build-docker@develop
        with:
          target_architecture: ${{ matrix.target_architecture }}
          docker_image: ${{ env.DEB_BUILD_DOCKER_IMAGE }}:${{ env.DEB_BUILD_DOCKER_TAG }}
          build_directory: ./artifacts

      # ------------------------------------------------------------------------

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      # - name: Upload Debian package artifacts
      #   uses: pi-top/debian-package-artifact-uploader@master
      #   with:
      #     path: ./artifacts
      #     deb_only: true
      #     # deb_only_name: "deb"
      #     deb_src_only: true
      #     # deb_src_name: "deb-src"
      #     prefix: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-"
