name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  DEB_BUILD_DOCKER_IMAGE: "pitop/pi-top-os-deb-build"
  DEB_BUILD_DOCKER_TAG: "buster-backports-develop"
  CHANGELOG_AUTHOR_NAME: "pi-top"
  CHANGELOG_AUTHOR_EMAIL: "deb-maintainers@pi-top.com"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Patch changelog (snapshot)
        uses: pi-top/git-debian-changelog-bump-action@develop
        with:
          release: false
          author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
          author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}

      - name: Determine architecture to use from package info
        # If architecture is 'all', then it can be compiled on host architecture
        # All other pi-topOS cases require 'armhf'
        run: |
          target_architecture=amd64
          if grep '^Architecture:' debian/control | grep -q -v 'all'; then
            target_architecture=armhf
          fi
          echo "TARGET_ARCHITECTURE=${target_architecture}" >> $GITHUB_ENV

      - name: Build Debian package
        uses: pi-top/debian-package-build-action@develop
        with:
          target_architecture: ${{ env.TARGET_ARCHITECTURE }}
          docker_image: ${{ env.DEB_BUILD_DOCKER_IMAGE }}:${{ env.DEB_BUILD_DOCKER_TAG }}
          build_directory: ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "deb"
          path: "./artifacts/*.deb"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "deb-src"
          path: |
            ./artifacts/**
            !./artifacts/*.deb

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: "dsc"
      #     path: "./artifacts/**"
