name: Build (Bullseye)

on:
  pull_request:
    branches:
      - bullseye
  push:
    branches:
      - bullseye

env:
  UPLOAD_SNAPSHOT_BUILD: "true"
  REPO: "experimental"
  OS_TYPE: "debian"
  OS_VERSION: "bullseye"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Patch changelog (snapshot)
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}:/src \
            -e RELEASE=0 \
            pitop/gbp-dch-gen:latest

      - name: Build Debian package
        run: |
          mkdir -p /tmp/artifacts/{src,bin}
          docker run --rm \
            --volume ${{ github.workspace }}:/src \
            --volume /tmp/artifacts/bin:/build \
            -e LINTIAN_TAGS_TO_SUPPRESS="debian-changelog-line-too-long,spelling-error-in-changelog,unreleased-changelog-distribution" \
            pitop/deb-build:latest

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish Debian package(s)
        if: ${{ env.UPLOAD_SNAPSHOT_BUILD }} == "true"
        run: |
          cd /tmp/artifacts/bin/
          dsc_filename=(find . -name "*.dsc" | head -n1)
          PACKAGECLOUD_TOKEN=${{ secrets.PACKAGECLOUD_TOKEN }} \
            package_cloud \
              push --verbose \
              pi-top/${{ env.REPO }}/${{ env.OS_TYPE }}/${{ env.OS_VERSION }} \
              "${dsc_filename}"

      - name: Show PackageCloud page for package
        if: ${{ env.UPLOAD_SNAPSHOT_BUILD }} == "true"
        run: |
          echo "https://packagecloud.io/pi-top/${{ env.REPO }}/packages/${{ env.OS_TYPE }}/${{ env.OS_VERSION }}/${dsc_filename}"

      - name: Separate Debian source package files from binary
        run: |
          mv /tmp/artifacts/bin/* /tmp/artifacts/src/
          mv /tmp/artifacts/src/*.deb /tmp/artifacts/bin/

      - name: Upload Debian source package files
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-deb-src"
          path: "/tmp/artifacts/src/"

      - name: Upload Debian binary packages
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-deb"
          path: "/tmp/artifacts/bin/"
