name: Keep Pull Requests up-to-date with master

on:
  push:
    branches:
      - master

jobs:
  rebase:
    runs-on: ubuntu-20.04
    steps:
      - uses: maxkomarychev/pr-updater-action@v1.0.0
        with:
          # PAT needed to trigger other workflows
          token: ${{ secrets.REBASE_PAT }}
